--PACK v2.0

--PACIENTES
ALTER TABLE TPACIENTE DROP ORIGEM_CAD; COMMIT WORK;

--RECEITA
ALTER TABLE TRECEITA DROP POSOLOGIA; COMMIT WORK;

ALTER TABLE TRECEITA
ADD QTD_FRASCOS SMALLINT; COMMIT WORK;

ALTER TABLE TRECEITA
ADD QTD_POSOLOGIA SMALLINT; COMMIT WORK;

ALTER TABLE TRECEITA
ADD INTERVALO_POSOLOGIA SMALLINT; COMMIT WORK;

--PROCEDIMENTO
ALTER TABLE TPROCEDIMENTO
ADD DATA_PROC_LAN DATE; COMMIT WORK;